function [ data ] = mvpalab_filterdata( EEG,freq,cfg)
%MVPALAB_FILTERDATA Summary of this function goes here
%   Detailed explanation goes here

EEG = pop_firws(EEG,...
    'fcutoff', cfg.sf.fcutoff(freq),...
    'ftype', cfg.sf.ftype,...
    'wtype', cfg.sf.wtype,...
    'forder', cfg.sf.order,...
    'minphase', 0);

data = EEG.data;

end

